### ISSUE TITLE
Composer install fails

### ISSUE THREAD

**Issue by lenin-indigo** [Shoperti/Payme#54]
I can't install the package via composer with the instructions in the README.md

Steps to reproduce:
**1.-** Contents of the file _composer.json_:

```
{
    "require": {
        "shoperti/payme": "2.0-dev"
    }
}
```

**2.-** Run the following command:
`$ composer install`

**3.-** It shows me the next error:

```
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - The requested package shoperti/payme 2.0-dev exists as shoperti/payme[1.0.x-dev, dev-master, 2.0.x-dev] but these are rejected by your constraint.
```

If i use the version listed in the [Packagist](https://packagist.org/packages/shoperti/payme) composer installs correctly:

```
{
    "require": {
        "shoperti/payme": "2.0.x-dev"
    }
}
```

**Comment by joecohens** [comment]
You should have on your composer.json since we haven't tagged a stable version yet. We are about to release it.

```json
"minimum-stability": "dev",
"prefer-stable": true
```
