### ISSUE TITLE
Disable Guzzle SSL certificate verification

### ISSUE THREAD

**Issue by lenin-indigo** [Shoperti/Payme#55]
For development purpouses, i need to disable the **Guzzle** SSL certificate verification:
[http://docs.guzzlephp.org/en/latest/request-options.html#verify](http://docs.guzzlephp.org/en/latest/request-options.html#verify)

In localhost i get the next error:

> RequestException in CurlFactory.php line 187:
> cURL error 60: SSL certificate problem: unable to get local issuer certificate (see http://curl.haxx.se/libcurl/c/libcurl-errors.html)

I need to pass an option to the configuration, and change the method '**getHttpClient**' in the file **AbstractGateway.php**, something like:
```
    /**
     * Get a fresh instance of the Guzzle HTTP client.
     *
     * @return \GuzzleHttp\Client
     */
    protected function getHttpClient()
    {
		$verify = ( isset( $this->config['verify'] ) ) ? $this->config['verify'] : true ;
        return new GuzzleClient(['verify' => $verify ]);
    }
```

**Comment by GrahamCampbell** [comment]
👎 You should NEVER need to disable this. Doing so is a HUGE security risk.Especiallyy when you're dealing with something so sensitive as payments.

**Comment by joecohens** [comment]
I agree with Graham, you should never have to disable this option due security issues. Sorry.
